"""Validation. Nothing is written unless every check here passes.

Four tiers:
  1. Shape        — the declarative SPECS table below. Unknown keys are errors,
                    which is what stops dead fields accumulating in the schema.
  2. Referential  — every ref resolves, AND every id-shaped string found anywhere
                    (including buried in a prose sentence) names a real entity.
  3. Semantic     — cross-file contradictions: a deal whose company has no
                    diligence brief, a date in the future, an unanswered reply
                    that no thread accounts for.
  4. Link audit   — lives in make.py, after rendering.

SPECS is also the source of the data-contract section on the Build page, so the
documentation of the schema is generated by the thing that enforces it.
"""

import difflib

from .model import kind_of
from .util import ID_RE, as_date

STAGES = ["New", "Screening", "Diligence", "Partner review", "Committed", "Passed"]
SOURCE_KINDS = ["warm_intro", "portfolio_referral", "cofund", "inbound_cold", "conference"]
TIERS = ["core", "active", "dormant"]
PRIORITIES = [1, 2, 3, 4]
ACTIONS = ["respond_now", "batch", "delegate", "decline", "already_drafted"]
PROJECT_STATUS = ["On track", "At risk", "Blocked", "Shipped"]
AUTONOMY = ["acts", "drafts", "flags"]

DECISION_SPEC = {
    "question": {"type": "str"},
    "options": {"type": "list", "of": "str"},
    "recommendation": {"type": "str"},
    "why": {"type": "str"},
    "deadline": {"type": "date"},
    "cost_of_delay": {"type": "str"},
}

REL_SPEC = {
    "tier": {"type": "enum", "values": TIERS},
    "how_we_met": {"type": "str"},
    "last_contact": {"type": "date"},
    "last_contact_channel": {"type": "str"},
    "cadence_days": {"type": "int", "min": 1, "max": 400},
    "owed_reply": {"type": "bool"},
    "intro_paths": {"type": "list", "of": "any"},
    "note": {"type": "str"},
}

SUBSPECS = {"decision": DECISION_SPEC, "rel": REL_SPEC}

SPECS = {
    "person": {
        "id": {"type": "id", "prefix": "per"},
        "name": {"type": "str"},
        "title": {"type": "str"},
        "org": {"type": "ref", "kind": "co", "nullable": True},
        "email": {"type": "str"},
        "location": {"type": "str"},
        "tags": {"type": "list", "of": "str"},
        "rel": {"type": "obj", "spec": "rel", "optional": True},
    },
    "company": {
        "id": {"type": "id", "prefix": "co"},
        "name": {"type": "str"},
        "one_liner": {"type": "str"},
        "sector": {"type": "str"},
        "stage": {"type": "str"},
        "hq": {"type": "str"},
        "founded": {"type": "str"},
        "team": {"type": "list", "of": "ref", "kind": "per"},
    },
    "deal": {
        "id": {"type": "id", "prefix": "deal"},
        "company": {"type": "ref", "kind": "co"},
        "stage": {"type": "enum", "values": STAGES},
        "score": {"type": "int", "min": 0, "max": 10},
        "score_breakdown": {"type": "any"},
        "source": {"type": "any"},
        "owner": {"type": "ref", "kind": "per"},
        "first_seen": {"type": "date"},
        "updated": {"type": "date"},
        "round": {"type": "str"},
        "ask": {"type": "str"},
        "thesis_fit": {"type": "str"},
        "next_step": {"type": "str"},
        "needs_decision": {"type": "obj", "spec": "decision", "nullable": True},
    },
    "thread": {
        "id": {"type": "id", "prefix": "thr"},
        "from": {"type": "ref", "kind": "per"},
        "subject": {"type": "str"},
        "received": {"type": "date"},
        "priority": {"type": "enum", "values": PRIORITIES},
        "sla": {"type": "str"},
        "action": {"type": "enum", "values": ACTIONS},
        "ask": {"type": "str"},
        "why": {"type": "str"},
        "red_flags": {"type": "list", "of": "str"},
        "excerpt": {"type": "str"},
        "draft_reply": {"type": "str", "nullable": True},
        "about": {"type": "list", "of": "any"},
        "needs_decision": {"type": "obj", "spec": "decision", "nullable": True, "optional": True},
    },
    "meeting": {
        "id": {"type": "id", "prefix": "mtg"},
        "start": {"type": "str"},
        "end": {"type": "str"},
        "title": {"type": "str"},
        "kind": {"type": "str"},
        "attendees": {"type": "list", "of": "ref", "kind": "per"},
        "about": {"type": "list", "of": "any"},
        "prep": {"type": "any"},
        "needs_decision": {"type": "obj", "spec": "decision", "nullable": True, "optional": True},
    },
    "project": {
        "id": {"type": "id", "prefix": "prj"},
        "name": {"type": "str"},
        "status": {"type": "enum", "values": PROJECT_STATUS},
        "owner": {"type": "ref", "kind": "per"},
        "due": {"type": "date"},
        "summary": {"type": "str"},
        "blocked_on": {"type": "str", "nullable": True},
        "next_step": {"type": "str"},
        "people": {"type": "list", "of": "ref", "kind": "per"},
        "needs_decision": {"type": "obj", "spec": "decision", "nullable": True, "optional": True},
    },
    "agent": {
        "id": {"type": "id", "prefix": "agt"},
        "name": {"type": "str"},
        "feeds": {"type": "list", "of": "str"},
        "autonomy": {"type": "enum", "values": AUTONOMY},
        "schedule": {"type": "any"},
        "does": {"type": "str"},
        "inputs": {"type": "list", "of": "any"},
        "outputs": {"type": "list", "of": "any"},
        "escalates_when": {"type": "list", "of": "str"},
        "human_in_loop": {"type": "str"},
    },
}

COLLECTION_SPEC = {
    "people": "person",
    "companies": "company",
    "deals": "deal",
    "threads": "thread",
    "meetings": "meeting",
    "projects": "project",
    "agents": "agent",
}


# ---------------------------------------------------------------- tier 1: shape

def _check_value(value, spec, loc, store, errors):
    kind = spec["type"]

    if value is None:
        if not spec.get("nullable"):
            errors.append(f"{loc}: null is not allowed here")
        return

    if kind == "any":
        return
    if kind == "id":
        if not isinstance(value, str) or kind_of(value) != spec["prefix"]:
            errors.append(f"{loc}: expected an id starting '{spec['prefix']}_', got {value!r}")
    elif kind == "ref":
        if not isinstance(value, str):
            errors.append(f"{loc}: expected an id string, got {value!r}")
        elif value not in store.ids:
            errors.append(f"{loc}: unknown id {value!r}{_did_you_mean(value, store)}")
        elif kind_of(value) != spec["kind"]:
            errors.append(f"{loc}: expected a '{spec['kind']}_' id, got {value!r}")
    elif kind == "str":
        if not isinstance(value, str) or not value.strip():
            errors.append(f"{loc}: expected a non-empty string, got {value!r}")
    elif kind == "enum":
        if value not in spec["values"]:
            errors.append(f"{loc}: {value!r} is not one of {spec['values']}")
    elif kind == "int":
        if not isinstance(value, int) or isinstance(value, bool):
            errors.append(f"{loc}: expected an integer, got {value!r}")
        elif not (spec.get("min", -10**9) <= value <= spec.get("max", 10**9)):
            errors.append(f"{loc}: {value} is outside {spec.get('min')}..{spec.get('max')}")
    elif kind == "bool":
        if not isinstance(value, bool):
            errors.append(f"{loc}: expected true/false, got {value!r}")
    elif kind == "date":
        try:
            as_date(value)
        except (ValueError, TypeError):
            errors.append(f"{loc}: expected an ISO date, got {value!r}")
    elif kind == "list":
        if not isinstance(value, list):
            errors.append(f"{loc}: expected a list, got {value!r}")
            return
        inner = {"type": spec["of"]}
        if "kind" in spec:
            inner["kind"] = spec["kind"]
        for index, item in enumerate(value):
            _check_value(item, inner, f"{loc}[{index}]", store, errors)
    elif kind == "obj":
        if not isinstance(value, dict):
            errors.append(f"{loc}: expected an object, got {value!r}")
            return
        _check_record(value, SUBSPECS[spec["spec"]], loc, store, errors)


def _check_record(record, spec, loc, store, errors):
    for field, field_spec in spec.items():
        if field not in record:
            if not field_spec.get("optional"):
                errors.append(f"{loc}: missing required field '{field}'")
            continue
        _check_value(record[field], field_spec, f"{loc}.{field}", store, errors)

    for field in record:
        if field not in spec:
            near = difflib.get_close_matches(field, list(spec), n=1, cutoff=0.7)
            hint = f" — did you mean '{near[0]}'?" if near else ""
            errors.append(f"{loc}: unknown field '{field}'{hint}")


def _did_you_mean(value, store):
    near = difflib.get_close_matches(value, sorted(store.ids), n=1, cutoff=0.7)
    return f" — did you mean '{near[0]}'?" if near else ""


# ---------------------------------------------------- tier 2: referential

def _scan_prose(node, loc, store, errors):
    if isinstance(node, str):
        for hit in ID_RE.findall(node):
            if hit not in store.ids:
                errors.append(f"{loc}: text references unknown id {hit!r}{_did_you_mean(hit, store)}")
    elif isinstance(node, list):
        for index, item in enumerate(node):
            _scan_prose(item, f"{loc}[{index}]", store, errors)
    elif isinstance(node, dict):
        for key, value in node.items():
            _scan_prose(value, f"{loc}.{key}", store, errors)


# ------------------------------------------------------- tier 3: semantic

def _semantic(store, errors, warnings):
    today = store.today

    seen = {}
    for attr, records in store.by_kind.items():
        for record in records:
            if record["id"] in seen:
                errors.append(f"duplicate id {record['id']!r} in {attr} and {seen[record['id']]}")
            seen[record["id"]] = attr

    # Nothing in the world may be dated after the day the world is set on.
    for attr, records in store.by_kind.items():
        for record in records:
            for field in ("last_contact", "received", "updated", "first_seen", "start", "end"):
                value = record.get(field) or (record.get("rel") or {}).get(field)
                if value and str(value)[:10] > today:
                    errors.append(f"{attr}/{record['id']}.{field}: {value} is after meta.today ({today})")

    for deal in store.deals:
        stage_index = STAGES.index(deal["stage"])
        has_brief = deal["company"] in store.diligence
        if stage_index >= STAGES.index("Diligence") and deal["stage"] != "Passed" and not has_brief:
            errors.append(f"deals/{deal['id']}: stage '{deal['stage']}' but "
                          f"data/diligence/{deal['company']}.json does not exist")

    for company_id in store.diligence:
        if company_id not in store.ids:
            errors.append(f"diligence/{company_id}.json: no such company")
        elif store.deal_for_company(company_id) is None:
            warnings.append(f"diligence/{company_id}.json: no deal references this company")

    # If someone wrote on the 26th, "last contact" cannot be the 24th. This is the
    # exact shape of contradiction that survives a careful read and then gets
    # noticed by the one person you did not want to notice it.
    newest_from = {}
    for thread in store.threads:
        sender = thread["from"]
        day = thread["received"][:10]
        if day > newest_from.get(sender, ""):
            newest_from[sender] = day
    for person in store.people_with_rel():
        latest = newest_from.get(person["id"])
        if latest and person["rel"]["last_contact"] < latest:
            errors.append(
                f"people/{person['id']}.rel.last_contact is {person['rel']['last_contact']} "
                f"but they sent a message on {latest}")

    for person in store.people_with_rel():
        rel = person["rel"]
        if rel["owed_reply"]:
            open_threads = [t for t in store.threads
                            if t["from"] == person["id"] and t.get("action") != "already_drafted"]
            if not open_threads and "no thread" not in rel["note"].lower():
                warnings.append(f"people/{person['id']}: owed_reply is true but no open "
                                f"thread explains it")
        for path in rel["intro_paths"]:
            for step in path:
                if step not in store.ids:
                    errors.append(f"people/{person['id']}.rel.intro_paths: unknown id {step!r}")

    for thread in store.threads:
        if thread["priority"] == 1 and thread.get("action") == "batch":
            warnings.append(f"threads/{thread['id']}: priority 1 but action 'batch'")

    for meeting in store.meetings:
        if meeting["start"] > meeting["end"]:
            errors.append(f"meetings/{meeting['id']}: start is after end")

    # Orphan check, but only for entities that are meant to be referenced.
    # Threads, meetings and projects are entry points — they point outward and
    # nothing points back, which is correct rather than dead weight.
    referenced = set(store._backlinks)
    for attr in ("people", "companies"):
        for record in store.by_kind.get(attr, []):
            if record["id"] not in referenced and record["id"] != store.meta["principal"]:
                warnings.append(f"{attr}/{record['id']}: nothing references it")


# ---------------------------------------------------------------- entry point

def validate(store):
    errors, warnings = [], []

    if store.meta["principal"] not in store.ids:
        errors.append(f"meta.principal: unknown id {store.meta['principal']!r}")

    for attr, spec_name in COLLECTION_SPEC.items():
        spec = SPECS[spec_name]
        for index, record in enumerate(store.by_kind.get(attr, [])):
            loc = f"{attr}[{index}]"
            if isinstance(record, dict) and "id" in record:
                loc = f"{attr}/{record['id']}"
            _check_record(record, spec, loc, store, errors)

    for attr, records in store.by_kind.items():
        for record in records:
            _scan_prose(record, f"{attr}/{record['id']}", store, errors)
    for company_id, brief in store.diligence.items():
        _scan_prose(brief, f"diligence/{company_id}", store, errors)

    _semantic(store, errors, warnings)
    return errors, warnings
